//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Beauty_Saloon
    {
        [Key]
        public int Saloon_id { get; set; }
        public string Saloon_name { get; set; }
        public string saloon_service { get; set; }
        public string Time { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
    }
}
