//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beauty_Saloon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beauty_Saloon()
        {
            this.Saloon_booking = new HashSet<Saloon_booking>();
        }
    
        public int Saloon_id { get; set; }
        public string Saloon_name { get; set; }
        public string saloon_service { get; set; }
        public string Time { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saloon_booking> Saloon_booking { get; set; }
    }
}
