//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Key]
        public int Employee_id { get; set; }
        public int Login_id { get; set; }
        public string Employee_name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
