//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie_ticket
    {
        [Key]
        public int Movie_id { get; set; }
        public string Movie_name { get; set; }
        public string Screen { get; set; }
        public string Genre { get; set; }
        public string Time { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
    }
}
