//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_bookings
    {
        public int Movie_bookings_id { get; set; }
        public int Voyager_id { get; set; }
        public int Movie_id { get; set; }
        public Nullable<int> seat { get; set; }
        public string Date { get; set; }
        public string Total { get; set; }
        public string Status { get; set; }
    
        public virtual Movie_ticket Movie_ticket { get; set; }
        public virtual Voyager Voyager { get; set; }
    }
}
