//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [Key]
        public int Payment_id { get; set; }
        public Nullable<int> Booking_details_id { get; set; }
        public string Booking_for { get; set; }
        public string Amount { get; set; }
        public string Date { get; set; }
    
        public virtual Booking_details Booking_details { get; set; }
    }
}
