//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseshipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saloon_booking
    {
        public int Saloon_booking_id { get; set; }
        public int Voyager_id { get; set; }
        public int Saloon_id { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
    
        public virtual Beauty_Saloon Beauty_Saloon { get; set; }
        public virtual Voyager Voyager { get; set; }
    }
}
